# Generated by Django 5.1.1 on 2024-11-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='step',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
